logging:
  file:
    path: /var/log/
    name: webdav.log
#    max-size: 200MB
  level:
    okhttp3: warn
    root: info
#  level:
#    net:
#      sf:
#        webdav: trace

aliyundrive:
  auth:
    enable: true
    username: admin
    password: admin

server:
  tomcat:
    connection-timeout: 1d
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
